name: Build

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
  
      - name: Nuget Restore
        run: nuget restore $Env:GITHUB_WORKSPACE\SQLRecon\SQLRecon\SQLRecon.sln 
      
          
      - name: Build Tools
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SQLRecon\SQLRecon\SQLRecon\SQLRecon.csproj /property:Configuration=Release
      

      - uses: actions/upload-artifact@master
        with:
          name: SQLRecon
          path: SQLRecon\SQLRecon\SQLRecon\bin\Release\SQLRecon.exe

